### ISSUE TITLE
Fix jQuery deprecation warnings

### ISSUE THREAD

**Issue by dpeyou** [wpovernight/woocommerce-improved-external-products#2]

**Comment by dpeyou** [comment]
Wasn't able to detect any deprecation warnings, however some deprecated jQuery was found here https://github.com/wpovernight/woocommerce-improved-external-products/blob/ba54052eacfec1f0b50f7d46f1f4486a68835df4/includes/wc-improved-external-products-settings.php#L326

**Comment by Spreeuw** [comment]
Shows in the console for me, see:
![iepp-jquery-migrate-warning](https://user-images.githubusercontent.com/3217773/113921597-7cfa9000-97e6-11eb-89ad-53d8bb46bd7f.png)
Clicking that highlights the line with the `.click()` error.

The script itself needs a bit of cleanup too, this is better:
```js
jQuery( function ( $ ) {
	$('.hidden-input').on('click',function() {
		$(this).closest('.hidden-input').prev('.pro-feature').show('slow');
		$(this).closest('.hidden-input').hide();
	});

	$("input.wcbulkorder-disabled").attr('disabled',true);
});
```
